[package]
name = "vidoc"
version = "0.0.1"
authors = [
  "Gaëtan André <rvlander@gaetanandre.eu>",
  "Victor Berger <victor.berger@m4x.org>", 
  "Drakulix (Victor Brekenfeld)"
]
license = "TBD"
publish = false
edition = "2018"

[dependencies]
slog = { version = "2.1.1" }
slog-term = "2.3"
slog-async = "2.2"
rand = "0.6"
glium = { version = "0.23.0", default-features = false }
wayland-server = "0.23"
xkbcommon = "0.4.0"
bitflags = "1.2.1"
freedesktop_entry_parser = "0.2.0"
dirs = "2.0.2"
linicon = "0.3.0"
image = "0.23.2"

[dependencies.smithay]
path = ".."
default-features = false
features = [ "renderer_glium", "backend_egl", "wayland_frontend" ]

[build-dependencies]
gl_generator = "0.10"

[features]
default = [ "winit", "egl", "udev"]
egl = [ "smithay/native_lib" ]
winit = [ "smithay/backend_winit" ]
udev = [ "smithay/backend_libinput", "smithay/backend_drm_legacy", "smithay/backend_drm_gbm", "smithay/backend_drm_egl", "smithay/backend_udev", "smithay/backend_session" ]
logind = [ "smithay/backend_session_logind" ]
